spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb

server:
  port: 8080

spring-doc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true